---

- name: Prepare
  hosts: k8s
  gather_facts: no
  tasks:
    - name: Install python
      raw: "apt-get update && apt-get -y install python-pip"
    #- name: Fix DNS servers
    #- net_system:
    #-   name_servers:
    #-     - 8.8.8.8
    #-     - 8.8.4.4

      #- name: Harden
      #  vars:
      #    ansible_user: root
      #  hosts: k8s
      #  roles:
      #    - role: githubixx.harden-linux
      #      tags: role-harden-linux
