---

- name: githubixx.cfssl
  src: https://github.com/githubixx/ansible-role-cfssl.git
  scm: git
  version: 3.0.0+1.2.0

- name: githubixx.kubernetes-ca
  src: https://github.com/githubixx/ansible-role-kubernetes-ca.git
  scm: git
  version: 7.0.0+1.12.3

- name: githubixx.kubectl
  src: https://github.com/githubixx/ansible-role-kubectl.git
  scm: git
  version: 7.0.0+1.13.0

- name: githubixx.harden-linux
  src: https://github.com/githubixx/ansible-role-harden-linux.git
  scm: git
  version: v3.1.0

- name: githubixx.kubernetes-flanneld
  src: https://github.com/githubixx/ansible-role-flanneld.git
  scm: git
  version: 7.0.1+0.10.0

- name: githubixx.docker
  src: https://github.com/githubixx/ansible-role-docker.git
  scm: git
  version: 5.1.0+18.06.1

- name: githubixx.etcd
  src: https://github.com/githubixx/ansible-role-etcd.git
  scm: git
  version: 7.0.0+3.2.24

- name: githubixx.kubernetes-controller
  src: https://github.com/githubixx/ansible-role-kubernetes-controller.git
  scm: git
  version: 6.0.0+1.13.2

- name: githubixx.kubernetes-worker
  src: https://github.com/githubixx/ansible-role-kubernetes-worker.git
  scm: git
  version: 8.0.0+1.13.2
