---

#- import_playbook: prepare.yml
#- import_playbook: ca.yml

- name: Gather facts
  hosts: k8s
  tasks:
    - setup:

- import_playbook: playbooks/kubeauthconfig/kubelets.yml
- import_playbook: playbooks/kubeauthconfig/kube-proxy.yml
- import_playbook: playbooks/kubeauthconfig/kube-controller-manager.yml
- import_playbook: playbooks/kubeauthconfig/kube-scheduler.yml
- import_playbook: playbooks/kubeauthconfig/kube-admin-user.yml
- import_playbook: playbooks/kubeencryptionconfig/kubeencryptionconfig.yml

- name: Install kubectl
  hosts: k8s_kubectl
  roles:
    - role: githubixx.kubectl
      tags: role-kubectl

- name: Install etcd
  hosts: k8s_etcd
  roles:
    - role: githubixx.etcd
      tags: role-etcd

- name: Prepare all nodes
  hosts: k8s:children
  roles:
    - role: githubixx.kubernetes-flanneld
      tags: role-kubernetes-flanneld
    - role: githubixx.docker
      tags: role-docker
      
- name: Initialize Kubernetes cluster
  hosts: k8s_controller
  roles:
    - role: githubixx.kubernetes-controller
      tags: role-kubernetes-controller
  tasks:
    - name: STOP
      command: "false"

- name: Join workers to cluster
  hosts: k8s_worker
  roles:
    - role: githubixx.kubernetes-worker
      tags: role-kubernetes-worker
